config/routes.rb
PracticalKnowledge::Application.routes.draw do

  # Root Homepage
  root                  to: 'public/pages#home'
  get '/:locale',       to: 'public/pages#home'

  # Local routes
  scope '/:locale' do

    resources :errors, only: [:show]

    namespace :admin do
      resources :users, :countries, :entries, :categories

      resources :courses do
        resources :lessons
      end

      # Attachments resource
      match '/attachments/:model/:id/:attachment/:return_url/(.:format)' => 'attachments#destroy', as: :attachment, via: [:delete, :get, :post]
    end

    scope module: 'public' do

      # Search resource aliases
      get     'search',                       to: 'searches#show'

      # Pages resource aliases
      get     '',                             to: 'pages#show', id: 'home'
      get     'about',                        to: 'pages#show', id: 'about'
      get     'terms-and-conditions',         to: 'pages#show', id: 'terms_and_conditions'
      get     'privacy-policy',               to: 'pages#show', id: 'privacy_policy'
      get     'developers',                   to: 'pages#show', id: 'developers'

      # Sessions resource aliases
      get     'login',                        to: 'sessions#new'
      post    'login',                        to: 'sessions#create'
      get     'logout',                       to: 'sessions#destroy'

      # User resource aliases
      get     'user/register',                to: 'users#new'
      post    'user/register',                to: 'users#create'
      get     'user/registered/:token',       to: 'users#created'
      get     'user/activate/:token',         to: 'users#activate'
      get     'user/activated/:token',        to: 'users#activated'
      get     'user/edit',                    to: 'users#edit'
      patch   'user/edit',                    to: 'users#update'
      get     'user/delete',                  to: 'users#delete'
      patch   'user/delete',                  to: 'users#activate_removal'
      get     'user/remove/:token',           to: 'users#destroy'
      get     'user/removed/:token',          to: 'users#removed'

      # Contact messages
      get     'contact',                      to: 'contact_messages#new'
      post    'contact',                      to: 'contact_messages#create'

      # Email change aliases
      get     'user/email-change',            to: 'email_changes#new'
      post    'user/email-change',            to: 'email_changes#create'
      get     'user/email-change/:token',     to: 'email_changes#update'

      # Password change aliases
      get     'user/password-change',         to: 'password_changes#edit'
      put     'user/password-change',         to: 'password_changes#update'

      # Password reset aliases
      get     'user/password-reset',          to: 'password_resets#new'
      post    'user/password-reset',          to: 'password_resets#create'
      get     'user/password-reset/:token',   to: 'password_resets#edit'
      put     'user/password-reset/:token',   to: 'password_resets#update'

      # Users resource
      resources :users do
        member do
          get 'created'             # Information page that activation email was sent.
          get 'activate'            # Activate user account.
          get 'activated'           # Welcome page for activated user.
          get 'delete'              # Form to remove account.
          patch 'activate_removal'  # Sent an email message with confirmation link for removal process.
          get 'removed'             # Message that account had been removed.
        end

        # Password Change resource
        resource :password_change,  only: [:edit, :update]

        # Email Change resource
        resource :email_change,  only: [:new, :create, :update]
      end

      # Password reset resource
      resources :password_resets, only: [:new, :create, :edit, :update] do
        collection do
          get 'created'
        end
      end

      # Pages resource
      resources :pages, only: [:show]

      # Contact messages resource
      resources :contact_messages,     only: [:new, :create]

      # Entries resource
      resources :entries,     only: [:show]

      # Categories resource
      # resources :categories,  only: [ :show ]

      # Courses resource
      resources :courses,     only: [:index, :show]

      # Search resource
      resource :searches,    only: [:show]

      # Sessions resource
      resource  :sessions,    only: [:new, :create, :destroy]

      # Dashboard resource
      resource  :dashboard,   only: [:show]

    end

  end

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/base_model/category.rb
class BaseModel::Category < ActiveRecord::Base
  self.table_name = 'category'

  has_many :courses

  validates :name,              presence:     true,
                                length:       1..100
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController
  helper_method :sort_column, :sort_direction

  # GET /admin/categories
  # GET /admin/categories.json
  def index
    @categories = BaseModel::Category.paginate(:page => params[:page]).order(sort_column + " " + sort_direction)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /admin/categories/1
  # GET /admin/categories/1.json
  def show
    @category = BaseModel::Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /admin/categories/new
  # GET /admin/categories/new.json
  def new
    @category = BaseModel::Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /admin/categories/1/edit
  def edit
    @category = BaseModel::Category.find(params[:id])
  end

  # POST /admin/categories
  # POST /admin/categories.json
  def create
    @category = BaseModel::Category.new(params[:admin_category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to :action => "index", notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/categories/1
  # PUT /admin/categories/1.json
  def update
    @category = BaseModel::Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:admin_category])
        format.html { redirect_to :action => "index", notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/categories/1
  # DELETE /admin/categories/1.json
  def destroy
    @category = BaseModel::Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to admin_categories_url }
      format.json { head :no_content }
    end
  end

  private

  def category_params
    params.require(:base_model_category).permit(:name)
  end

  def sort_column
    BaseModel::Category.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/views/admin/categories/_form.html.haml
.form-container
  = simple_form_for @category, :url => (@category.new_record? ? admin_categories_path() : admin_category_path(@category.id)), :html => {:class => 'form-content' } do |f|
    = f.error_notification
    = f.input :name, :input_html => { :maxlength => 32 }
    .control-group
      .controls
        = f.button :submit, (@category.new_record? ? t("button.create") : t("button.update")), :class => 'btn btn-inverse'

app/views/admin/categories/_menu.html.haml
.menu.navbar
  .navbar-inner
    %ul.nav
      %li{ class: ('active' if action?('index')) }= link_to t('admin.categories.link.categories'), admin_categories_path, class: 'nav-button'
      %li{ class: ('active' if action?('new', 'create')) }= link_to t('admin.categories.link.new_category'), new_admin_category_path, class: 'nav-button'
      - if defined?(buttons)
        - buttons.each do |button|
          %li= link_to t(button[:label]), button[:url], method: button[:method], confirm: button[:confirm].present? ? t(button[:confirm]) : nil, class: 'nav-button'

app/views/admin/categories/edit.html.haml
%h2= t 'admin.categories.header.edit_category'
= render partial: 'menu', locals: { buttons: [ { label: 'button.show_public', url: courses_path(category: @category.id) }, { label: 'button.show_overview', url: admin_category_path(@category.id) },  { label: 'button.delete', url: admin_category_path(@category.id), method: :delete, confirm: 'label.confirm_delete' } ] }
= render partial: 'form'

app/views/admin/categories/index.html.haml
%h2= t 'admin.categories.header.admin_categories'
= render :partial => "menu"
#categories
  %table.table.table-hover.table-bordered.admin-index-table
    %tbody
      %tr
        %th.header= sortable 'name', t('admin.categories.label.name')
        %th
    - @categories.each do |category|
      %tr
        %td.title-column= link_to category.name, admin_category_path(category.id), class: 'title-link'
        %td.options-column
          = link_to t('link.show'), admin_category_path(category.id), class: "btn btn-mini"
          = link_to t('link.edit'), edit_admin_category_path(category.id), class: "btn btn-mini"
          = link_to t('link.delete'), admin_category_path(category.id), method: :delete, data: { confirm: t('description.are_you_sure_question') }, class: "btn btn-mini btn-danger"
  = will_paginate @categories

app/views/admin/categories/new.html.haml
%h2= t 'admin.contries.header.new_category'
= render :partial => "menu"
= render :partial => "form"

app/views/admin/categories/show.html.haml
%h2= t 'admin.courses.header.show_course'
= render partial: 'menu', locals: { buttons: [ { label: 'button.show_public', url: courses_path(category: @category.id), }, { label: 'button.edit', url: edit_admin_category_path(@category.id) },  { label: 'button.delete', url: admin_category_path(@category.id), method: :delete, confirm: 'label.confirm_delete' } ] }
.admin-show
  .admin-show-input.admin-show-element
    .admin-show-label= t 'label.name'
    .admin-show-value= @category.name